sudo: required
language: node_js
node_js:
  - "9"
cache:
  directories:
    - node_modules
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  - npm run lint:es
  - npm run lint:solium
  - npm run ganache
  - sleep 10
  - truffle migrate
  - truffle test
  - npm run stop
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
